Updated README.md for GCI cohort docs task
OpenSRP/openmrs-module-cohort pull request #71
Opened 2016-12-05 07:34 UTC by Magicpotatoes2

2016-12-05 07:41 UTC, bholagabbar requested changes
Kindly make the changes, keep the formatting neat, clean and appealing. Don't be in a hurry!

2016-12-05 07:41 UTC, bholagabbar commented on README.md
> +_Created by Unknown User (ahabib), last modified by Unknown User (bholagabbar) on 2016-08-25_
remove this

2016-12-05 07:41 UTC, bholagabbar commented on README.md
> +* cohorts,
Too many spaces between bullets. Make it cohesive

2016-12-05 07:41 UTC, bholagabbar commented on README.md
> +* cohort typ
typo. It's 'type'

2016-12-05 07:41 UTC, bholagabbar commented on README.md
> +#### Video for Installation Of The Module
Remove this section, it includes an older version. I'm gonna put up a task to demo the new cohort module

2016-12-05 07:41 UTC, bholagabbar commented on README.md
> +## Quick Demonstration
Remove this for now as well

2016-12-05 07:41 UTC, bholagabbar commented on README.md
> +##### Note
REmove

2016-12-05 09:46 UTC, Magicpotatoes2 commented
Ok, I think I made the changes. I also improved other layout formats.

2016-12-05 10:17 UTC, Magicpotatoes2 commented
sorry which lines to remove? thanks

2016-12-06 06:13 UTC, bholagabbar requested changes

2016-12-06 06:13 UTC, bholagabbar commented on README.md
> +* [**Shreyrans' GSoC '16 Blog posts**](http://blog.shreyanssheth.com/)
Well you spelt my name wrong

2016-12-06 06:13 UTC, bholagabbar commented on README.md
> +* cohorts
The cohort attributes need to be further nested like this

* Dog
    * German Shepherd
    * Belgian Shepherd
        * Malinois
        * Groenendael
        * Tervuren
* Cat
    * Siberian
    * Siamese

2016-12-06 06:13 UTC, bholagabbar commented on README.md
> +* cohorts
@Magicpotatoes2 you did not do this

2016-12-06 06:13 UTC, bholagabbar commented on README.md
> +* **Project Pages**: [**Cohort Module**](https://wiki.openmrs.org/display/~sharonvarghese/Cohort+Module)**, **[**Cohort Module Enhacements**](https://wiki.openmrs.org/display/projects/Cohort+Module+E
Buggy markdown. Stray * symbol

2016-12-06 06:13 UTC, bholagabbar commented on README.md
> -The purpose of the [OpenMRS Cohort Module](https://wiki.openmrs.org/display/projects/Cohort+Module) is to manage Cohort related Data, Types, Attributes, Attribute Types and Members while using REST t
Add an introductory paragraph about the cohort module, like it was before you modified the REAMDE

2016-12-06 09:31 UTC, Magicpotatoes2 commented
I am very sorry about the half-complete task. I forgot to compare with the [Cohort wiki](https://wiki.openmrs.org/display/projects/Cohort+Module) after adding my changes based on your comments. I promise I will do better next time.

I have a question: may I fix spelling errors? They are just simple ones like `an` supposed to be `and` and etc. Thank you.

2016-12-06 13:46 UTC, bholagabbar commented
@Magicpotatoes2 That's alright. Take your time learning but make sure you complete your tasks before submitting. Make as many changes as you want, make the spelling changes, correct everything and only then resubmit it

2016-12-07 10:46 UTC, bholagabbar requested changes

2016-12-07 10:46 UTC, bholagabbar commented on README.md
> -The purpose of the [OpenMRS Cohort Module](https://wiki.openmrs.org/display/projects/Cohort+Module) is to manage Cohort related Data, Types, Attributes, Attribute Types and Members while using REST t
REST isn't needed in **bold**

2016-12-07 10:46 UTC, bholagabbar commented on README.md
> +##### What's a cohort?
Slightly bigger. #### What's a cohort is fine

2016-12-07 10:47 UTC, bholagabbar commented
@Magicpotatoes2 This looks good. Make the small changes I told you and *Squash your commits*. This means, that you have to squash your 5 commits into 1 commit. Look up google to see how to do this (squash commits).

2016-12-08 07:38 UTC, Magicpotatoes2 commented
@bholagabbar I've done it! Squashed **all** commits into one big one.

2016-12-08 10:46 UTC, merged

2016-12-08 10:52 UTC, bholagabbar commented
@Magicpotatoes2 why haven't you submitted the GCI task yet?

2016-12-08 12:39 UTC, Magicpotatoes2 commented
@bholagabbar Done! :smile: